  CREATE TABLE "EASY"."USUARIO"
   (
    "ID" NUMBER PRIMARY KEY,
	"FIRSTNAME" VARCHAR2(60 BYTE) NOT NULL,
    "LASTNAME" VARCHAR2(60 BYTE),
	"PASSWORD" VARCHAR2(20 BYTE)NOT NULL,
	"EMAIL" VARCHAR2(60 BYTE),
	"NUMBERPHONE" VARCHAR2(20 BYTE),
	"TIPEDOCUMENT" VARCHAR2(20 BYTE),
	"NUMDOCUMENT" NUMBER
   );